---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "k8s-node-hpa"
  labels:
    app: "k8s-node"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "k8s-node"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
