name: ci_workflow

on:
  push:

permissions:
  actions: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  node_build_workflow:
    uses: ./.github/workflows/build-pipeline.yml
  node_test_workflow:
    uses: ./.github/workflows/test-pipeline.yml
    needs: node_build_workflow
  node_quality_workflow:
    uses: ./.github/workflows/quality-pipeline.yml
    secrets: inherit
    needs: node_test_workflow
